blank_issues_enabled: false
contact_links:
  - name: "\U00002754 Ask a question"
    url: https://github.com/jvgomg/panda-css-presets/discussions
    about: Ask questions and discuss topics with other community members