name: Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - edited
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  prettier:
    name: Format
    # Don't run on the first run after creating from template. (run_number == 1).
    if: github.run_number != 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run Biome
        run: pnpm format

  tests:
    name: Unit Tests
    # Don't run on the first run after creating from template. (run_number == 1).
    if: github.run_number != 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run tests
        run: pnpm test

  types:
    name: TypeScript
    # Don't run on the first run after creating from template. (run_number == 1).
    if: github.run_number != 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run TypeScript type check
        run: pnpm typecheck